### ISSUE TITLE
change_group_sizes and related functions not available.

### ISSUE THREAD

**Issue by ghost** [mattreecebentley/plf_stack#1]
Hello !! After a couple compilation error, I did a simple crtl-F on my file and in  the repository. it seems that change_group_sizes and alike are not present anymore, but are still documented on your website. I don't have an urgent need, but it would be great to know if they are going to be added soon/ removed. My repo version dates from 19/09/2020, so this problem is present at least from this point in time. I will update my repo.

**Comment by mattreecebentley** [comment]
Hi there-
I will update the documentation, see the changelog for v1.43:
 v1.43

free_unused_memory() renamed to trim(). Macro renaming and updating. set_block_capacity_limits() renamed to reshape(), set_minimum_block_capacity_limit() and set_maximum_block_capacity_limit() removed. Removal of unnecessary assertions. Incorrect min/max block limits now results in a throw(). [[nodiscard]] added to empty() under C++20.

If you think the minimum/maximum variants are worth keeping let me know why.
Thanks for pointing that out-

**Comment by ghost** [comment]
If you know that your data is coming in groups of let'say 100, and then another 100, and then 100 again etc but you don't know when it is gonna stop.
Having the size of the group set at 100 would allow to allocate the right amount of memory each time, and not ending up with a group of 100 * (2 ^23) for exemple. Maybe this can be acomplished with other functions, but witch ones ? 

ASCII sheme:
1) prefered solution:
|100| -|100|-|100|-|100|-...

2) wanna avoid:

|100|-|200|-|400|-. . . -|12800|
                                    ^end of data after 100, 12700 'spaces' unused.

**Comment by mattreecebentley** [comment]
You can either set that with the appropriate constructor, or with reshape
at a later point. My question was not whether reshape or the constructor
were useful, it was whether the function which sets only min block size was
useful.
